#!/usr/bin/env python3
from setup_utils import *
import os

def undeploy():
    app = actions.getAppName("authn.delegating")
    if app:
        actions.undeploy(app)

actions, arg, props = getActions("setup.properties", [])

prop_name = "run.properties"
prop_list = ["secretToken", "ip"]

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()

if arg == "INSTALL":
    properties = getProperties(prop_name, prop_list)

    try:
        undeploy()
        ovfiles = [[prop_name, "WEB-INF/classes"]]
        if os.path.exists("logback.xml"):
            ovfiles.append(["logback.xml", "WEB-INF/classes"])
        actions.deploy(deploymentorder=80, files=ovfiles)
    except Exception as e:
        abort(str(e))

if arg == "UNINSTALL":
    try:
        undeploy() 
    except Exception as e:
        abort(str(e))
